SQL-906: Remove dialect option from JDBC API
mongodb/mongo-jdbc-driver pull request #104
Opened 2022-06-01 15:34 UTC by mattChiaravalloti

This PR removes the `DIALECT` property from the `MongoDriver` class. This also requires removing the `MySQLIntegrationTest` class since there is no longer a way to create a `MySQLConnection` through the `MongoDriver` api. There is also some other clean up `MongoDriverTest` -- removing `DIALECT` testing -- and `build.gradle` -- removing the reference to `MySQLIntegrationTest`.

This PR does _not_ remove all of the now-dead code that supports the `MySQL` dialect. That should be done as part of a separate follow-up ticket that considers exactly how the codebase should be factored after the `MySQL` stuff is removed. For example, will we want to keep the abstract classes everywhere? Will we want to keep the `MongoSQL` prefix on everything? etc. This PR is just removing the dialect from the public-facing api by no longer supporting the `DIALECT` property.

2022-06-01 17:00 UTC, nbagnard requested changes
Just a quick comment regarding the property CONVERSION_MODE. If you can quickly remove it, that'd probably be best.

2022-06-01 17:28 UTC, mattChiaravalloti commented on src/main/java/com/mongodb/jdbc/MongoDriver.java
>      static final String CONVERSION_MODE = "conversionMode";
great catch! removed it as part of this since we don't want that to be allowed publicly anymore either 👍

2022-06-01 20:48 UTC, bucaojit approved these changes
LGTM!

2022-06-02 08:48 UTC, nbagnard approved these changes
LGTM! :)

2022-06-02 14:38 UTC, mattChiaravalloti commented
evergreen merge

2022-06-02 15:47 UTC, merged