SQL-668: bsontype can be an array or a single String.
mongodb/mongo-jdbc-driver pull request #73
Opened 2022-02-05 00:37 UTC by nbagnard

This PR handles decoding schema where bsontype is either a Set<String> or String.
It also implements a logic for transforming sets of types in bsontype in a list of anyOf and flattening anyOfs.

The assumptions I made for this are:
- `{
    "bsonType": "bool",
    "additionalProperties": false
}`
is not equals to 
`{
    "bsonType": "bool",
    "additionalProperties": true
}`
so the same type can be twice in the anyOf list if the other fields values are different.
- If bsonType is a set of types, there will be no duplicates. For example, no `bsontype: [string, object, bool, object]`

2022-02-10 19:41 UTC, rychipman requested changes
only one relatively minor request from me

2022-02-10 19:41 UTC, rychipman commented on src/main/java/com/mongodb/jdbc/JsonSchema.java
> +    public Set<String> bsonType;
```suggestion
    public BsonValue bsonType;
```
I like the idea of having this `JsonSchema` class (for use as a deserialization target) as something separate from `MongoJsonSchema` (for using everywhere else in the API). I'd suggest that we go even further towards just making this class just a "dumb" deserialization target:
- keep the raw BsonValue for the `bsonType` field
- put whatever array/string polymophism-handling logic we need in the function that converts this to a `MongoJsonSchema`

2022-02-15 05:39 UTC, pmeredit commented
> This PR handles decoding schema where bsontype is either a Set or String. It also implements a logic for transforming sets of types in bsontype in a list of anyOf and flattening anyOfs.
> 
> The assumptions I made for this are:
> 
> * `{ "bsonType": "bool", "additionalProperties": false }`
>   is not equals to
>   `{ "bsonType": "bool", "additionalProperties": true }`
>   so the same type can be twice in the anyOf list if the other fields values are different.

It's still correct to have the same type twice, so I think this is a good simplifying assumption.

> * If bsonType is a set of types, there will be no duplicates. For example, no `bsontype: [string, object, bool, object]`

2022-02-15 05:45 UTC, pmeredit requested changes
I still need to go over the latter half of this. The first half looks good, just a few small requests.

2022-02-15 05:45 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
> +            Set<String> bsonTypes = polymorphicBsonTypeToStringSet(baseSchema.bsonType);
I love this method name.

2022-02-15 05:45 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
> +            //  type in the list, the types will be inserted in the list  of anyOf to be handled as polymorphic type.
```suggestion
            //  type in the list, the types will be inserted in the list of anyOf to be handled as polymorphic type.
```

2022-02-15 05:45 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
> +            // Push down each bsontype into its own anyOf schema
Could you add an example here in the comment to clarify what this mean?

2022-02-15 13:52 UTC, pmeredit commented
As a small comment, could we avoid removing new lines from the end of all the files? It messes up the PR. If that is something we want to do, we should do it in a separate PR. But I assume this was some IDE setting :)

2022-02-23 19:07 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/JsonSchema.java
> +        return Objects.equals(bsonType, other.bsonType)
Is `equals` defined for `BsonValue`?

2022-02-23 19:09 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/JsonSchema.java
> +        return Objects.equals(bsonType, other.bsonType)
Yes, it is!

2022-02-23 19:22 UTC, pmeredit approved these changes
LGTM! Feel free to apply the comment suggestion or not.

2022-02-23 19:22 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
> +             *  }
perfect!

2022-02-23 19:22 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
> +            /** Push down each bsontype into its own anyOf schema.
```suggestion
            /** Push down each bsontype from a bsontype array into a separate bsonType in an anyOf schema.
```

I think my problem with this comment before is "its own anyOf" which seems like we would have one `anyOf` per `bsonType`.

2022-02-23 19:22 UTC, pmeredit commented on src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
> +                            .flatMap(
<3 `flatMap`. Combinators just make code so much easier to follow once you learn them.

2022-02-28 20:49 UTC, rychipman approved these changes
LGTM

2022-03-01 17:05 UTC, merged